services:
  - type: web
    name: techsolution-bot
    plan: free
    runtime: python3.9.16  # Versión específica compatible
    buildCommand: |
      python -m pip install --upgrade pip wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: ${TELEGRAM_TOKEN}
      - key: PYTHON_VERSION
        value: "3.9.16"  # Doble confirmación
