services:
  - type: web
    name: techsolution
    plan: free
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: ${TELEGRAM_TOKEN}
      - key: PYTHON_VERSION
        value: "3.9"
      - key: APP_URL
        value: ${APP_URL}
