services:
  - type: worker  # Cambiado de 'web' a 'worker' para evitar búsqueda de puertos
    name: techsolution-bot
    plan: free
    runtime: python
    pythonVersion: "3.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8111684515:AAGAb9QiR7Uuf9nmNdb4kVXN_-uvUND5xv0"
    # Configuraciones para optimizar el free tier:
    autoStart: true
    autoDeploy: true
    healthCheckPath: /health  # Ruta ficticia para evitar warnings
    healthCheckTimeout: 120s
